//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopingCartEF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Band_Product
    {
        [Key]
        public int BrandID { get; set; }
        public int ProductsID { get; set; }
        public string Note { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Product Product { get; set; }
    }
}
