//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopingCartEF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Brand
    {
        public Brand()
        {
            this.Band_Product = new HashSet<Band_Product>();
            this.Products = new HashSet<Product>();
        }
        [Key]
        public int BrandID { get; set; }
        public string ImageUrl { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Band_Product> Band_Product { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
