//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopingCartEF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Category
    {
        public Category()
        {
            this.Products = new HashSet<Product>();
        }
        [Key]
        [Display(Name ="ID")]
        [Required(ErrorMessage ="Bắt buộc nhập")]
        public int CategoryID { get; set; }
        [Display(Name ="Tên danh mục")]
        public string Name { get; set; }
        [Display(Name ="Mô tả chi tiết")]
        public string Description { get; set; }
        [Display(Name ="Hình ảnh")]
        [DataType(DataType.ImageUrl)]
        public string ImageUrl { get; set; }
        [Display(Name ="ID danh mục cha")]
        [Required (ErrorMessage ="Bắt buộc nhập")]
        public Nullable<int> ParentID { get; set; }
        [Display(Name = "ID danh mục cha")]
        [Required(ErrorMessage = "Sắp xếp")]
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> IsPublished { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
