//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopingCartEF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        public Customer()
        {
            this.Orthers = new HashSet<Orther>();
        }
        [Key]
        public int CustomerID { get; set; }
        [Required(ErrorMessage = "Tên không được trống")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Email không được trống")]
        [EmailAddress(ErrorMessage ="Email không hợp lệ")]
        
        [DataType(DataType.EmailAddress, ErrorMessage = "Bạn phải nhập email")]      
        public string Email { get; set; }


        public string Password { get; set; }
        public Nullable<int> Phone { get; set; }
        public string DOB { get; set; }
        public string Adress { get; set; }

        public virtual ICollection<Orther> Orthers { get; set; }
    }
}
