//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopingCartEF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PaymenMethod
    {
        public PaymenMethod()
        {
            this.Orthers = new HashSet<Orther>();
        }
    [Key]
        public int PaymenMethodsID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Orther> Orthers { get; set; }
    }
}
