//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopingCartEF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public Product()
        {
            this.Band_Product = new HashSet<Band_Product>();
            
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        [Display(Name="ID")]
        [Key]
        public int ProductsID { get; set; }

        [Display(Name = "Danh mục sản phẩm")]
        public Nullable<int> CategoryID { get; set; }
        [Display(Name = "Thương hiệu sản phẩm")]
        public Nullable<int> BrandID { get; set; }
        public string ImageUrl { get; set; }

        [Display(Name = "Tên sản phẩm")]
        [Required(ErrorMessage ="Tên sản phẩm bắt buộc nhập")]
         
        public string Name { get; set; }

        [Display(Name = "Mô tả")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        [Display(Name = "Giá")]
        [Required(ErrorMessage = "Giá sản phẩm bắt buộc nhập")]
        public double Price { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public string Detail { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }

        [Display(Name = "Sắp xếp")]
        public Nullable<int> SortOrder { get; set; }

        [Display(Name = "Hiển thị")]
        public Nullable<bool> IsPublished { get; set; }
    
        public virtual ICollection<Band_Product> Band_Product { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
